import Link from "next/link";

const links = [["Home", "/"], ["Use Cases", "/use-cases"], ["Docs", "/docs"], ["Blog", "/blog"], ["Pricing", "/pricing"], ["FAQ", "/faq"]] as const;

export function MarketingNav() {
 return <header className="border-b border-line/70 bg-paper/90"><nav aria-label="Marketing" className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="font-display text-2xl font-medium italic">Reteno</Link><div className="hidden items-center gap-6 md:flex">{links.map(([label, href]) => <Link key={href} href={href} className="text-sm text-muted hover:text-ink">{label}</Link>)}</div><div className="flex items-center gap-3"><Link href="/dashboard" className="hidden text-sm text-muted sm:block">Log in</Link><Link href="/get-started" className="rounded-full bg-ink px-4 py-2 text-sm font-medium text-white hover:bg-ink/85">Get Started</Link></div></nav><div className="flex overflow-x-auto border-t border-line/60 px-5 py-2 md:hidden">{links.map(([label, href]) => <Link key={href} href={href} className="shrink-0 px-3 py-1 text-xs text-muted">{label}</Link>)}</div></header>
}
export function MarketingFooter() { return <footer className="border-t border-line bg-white/45"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 sm:grid-cols-2 sm:px-8 lg:grid-cols-5"><div><p className="font-display text-2xl italic">Reteno</p><p className="mt-3 max-w-44 text-sm text-muted">Capture anywhere. Learn in one place.</p></div>{[["Product", ["Features", "Use Cases", "Pricing", "FAQ"]], ["Resources", ["Docs", "Blog"]], ["Company", ["About", "Contact"]], ["Legal", ["Privacy", "Terms"]]].map(([heading, items]) => <div key={heading as string}><p className="text-sm font-medium">{heading as string}</p><ul className="mt-3 space-y-2">{(items as string[]).map(x => <li key={x}><span className="text-sm text-muted">{x}</span></li>)}</ul></div>)}</div></footer> }
export function MarketingLayout({children}:{children:React.ReactNode}) { return <><MarketingNav/><main>{children}</main><MarketingFooter/></> }
